config/routes.rb
# == Route Map
#
#                          Prefix Verb     URI Pattern                                                                              Controller#Action
#                  comments_index GET      /comments/index(.:format)                                                                comments#index
#                 comments_create GET      /comments/create(.:format)                                                               comments#create
#                comments_destroy GET      /comments/destroy(.:format)                                                              comments#destroy
#                new_user_session GET      /users/login(.:format)                                                                   devise/sessions#new
#                    user_session POST     /users/login(.:format)                                                                   devise/sessions#create
#            destroy_user_session DELETE   /users/logout(.:format)                                                                  devise/sessions#destroy
# user_twitter_omniauth_authorize GET|POST /users/auth/twitter(.:format)                                                            users/omniauth_callbacks#passthru
#  user_twitter_omniauth_callback GET|POST /users/auth/twitter/callback(.:format)                                                   users/omniauth_callbacks#twitter
#               new_user_password GET      /users/password/new(.:format)                                                            devise/passwords#new
#              edit_user_password GET      /users/password/edit(.:format)                                                           devise/passwords#edit
#                   user_password PATCH    /users/password(.:format)                                                                devise/passwords#update
#                                 PUT      /users/password(.:format)                                                                devise/passwords#update
#                                 POST     /users/password(.:format)                                                                devise/passwords#create
#        cancel_user_registration GET      /users/cancel(.:format)                                                                  registrations#cancel
#           new_user_registration GET      /users/registration(.:format)                                                            registrations#new
#          edit_user_registration GET      /users/profile(.:format)                                                                 registrations#edit
#               user_registration PATCH    /users(.:format)                                                                         registrations#update
#                                 PUT      /users(.:format)                                                                         registrations#update
#                                 DELETE   /users(.:format)                                                                         registrations#destroy
#                                 POST     /users(.:format)                                                                         registrations#create
#                           users GET      /users(.:format)                                                                         users#index
#                            user GET      /users/:id(.:format)                                                                     users#show
#                      post_likes POST     /posts/:post_id/likes(.:format)                                                          likes#create
#                            like DELETE   /likes/:id(.:format)                                                                     likes#destroy
#                   post_comments GET      /posts/:post_id/comments(.:format)                                                       comments#index
#                                 POST     /posts/:post_id/comments(.:format)                                                       comments#create
#                         comment DELETE   /comments/:id(.:format)                                                                  comments#destroy
#                  post_bookmarks POST     /posts/:post_id/bookmarks(.:format)                                                      bookmarks#create
#                        bookmark DELETE   /bookmarks/:id(.:format)                                                                 bookmarks#destroy
#                           posts GET      /posts(.:format)                                                                         posts#index
#                                 POST     /posts(.:format)                                                                         posts#create
#                            post GET      /posts/:id(.:format)                                                                     posts#show
#                                 DELETE   /posts/:id(.:format)                                                                     posts#destroy
#                       home_home GET      /home/home(.:format)                                                                     home#home
#                            root GET      /                                                                                        posts#index
#              rails_service_blob GET      /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#       rails_blob_representation GET      /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#              rails_disk_service GET      /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#       update_rails_disk_service PUT      /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#            rails_direct_uploads POST     /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/create'
  get 'comments/destroy'
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                            registrations: 'registrations' },
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           edit: 'profile',
                           sign_up: 'registration' }
  resources :users, only: %i[index show]
  resources :posts, only: %i[index show create destroy] do
    resources :likes, only: %i[create destroy], shallow: true
    resources :comments, only: %i[index create destroy], shallow: true
    resources :bookmarks, only: %i[create destroy], shallow: true
  end

  get 'home/home'
  root to: 'posts#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  content    :string
#  user_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :content, presence: true, length: { minimum: 10 }
  validates :user, presence: true
end

app/controllers/posts_controller.rb
require 'faker'

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show destroy]

  def index
    page = params[:page]
    @posts = Post.all
                 .order(created_at: :desc)
                 .includes(:user, :likes)
                 .page(page)
    @my_likes = Like.where(user: current_user).pluck(:post_id)
    @my_bookmarks = Bookmark.where(user: current_user).includes(:post)
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.photo = params[:photo]
    if @post.save
      flash[:notice] = 'Post has been saved!'
    else
      flash[:alert] = 'Unable to save'
    end

    redirect_to posts_path
  end

  def show
    @likes = @post.likes.includes(:user)
    @my_likes = Like.where(user: current_user).pluck(:post_id)
    @bookmark = Bookmark.find_by(user: current_user, post: @post)
  end

  def destroy
    authorize @post
    if @post.destroy
      flash[:notice] = 'Post has been deleted'
    else
      flash[:alert] = 'This action is not authorized'
    end

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content, :photo)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_bookmark_actions.html.erb
<% unless bookmark.nil? %>
  <%= link_to '', bookmark_path(bookmark), method: :delete, remote: true, class: 'core-sprite bookmarked hide-text ml-auto', id: "bookmark-icon-post-#{post.id.to_s}" %>
<% else %>
  <%= link_to '', post_bookmarks_path(post), method: :post, remote: true, class: 'core-sprite bookmark hide-text ml-auto', id: "bookmark-icon-post-#{post.id.to_s}" %>
<% end %>

app/views/posts/_comment.html.erb
<div class="mb-2" id="comment-<%= comment.id %>">
  <% if comment.user == current_user %>
    <%= link_to '', comment_path(comment), method: :delete, remote: true, class: 'core-sprite delete-comment' %>
  <% end %>
  <span>
    <strong><%= comment.user.name %></strong>
  </span>
  <span><%= comment.content%></span>
</div>

app/views/posts/_comment_form.html.erb
<%= form_with(model: comment, url: [post, comment], remote: true, class: 'w-100') do |form| %>
<%= form.hidden_field :user_id, value: current_user.id %>
<%= form.hidden_field :post_id, value: post.id %>
<div class="form-group">
  <%= form.text_area :content, class: 'form-control comment-input border-0', placeholder: 'Add a comment', rows: 5 %>
</div>
<div class="form-group">
  <%= form.submit 'Send', class: 'btn btn-small btn-primary' %>
</div>
<% end %>

app/views/posts/_likes.html.erb
<div class="mt-2" id="like-text-post-<%= post.id.to_s%>">
  <div id="like-text-post-<%= post.id.to_s%>">
    <% if post.likes.count == 1 %>
      <strong><%= post.likes.last.user.name%></strong>
      likes this
      <% elsif post.likes.count > 1 %>
        <strong>
          <%= pluralize(post.likes.count, 'like')%></strong>
      <% end %>
    </div>
  </div>

app/views/posts/_likes_actions.html.erb
<% if my_likes.include?(post.id) %>
  <%= link_to '', like_path(post), method: :delete, remote: true, class: 'core-sprite loved hide-text', id: "like-icon-post-#{post.id.to_s}" %>
<% else %>
  <%= link_to '', post_likes_path(post), method: :post, remote: true, class: 'core-sprite love hide-text', id: "like-icon-post-#{post.id.to_s}" %>
<% end %>

app/views/posts/_post.html.erb
<div class="card mt-3">
  <div class="card-header">
    <%= link_to user_path(post.user), class: 'no-text-decoration' do %>
    <%= gravatar_image_tag post.user.email, gravatar: { size: 50 }, alt: 'Profile Picture', class: 'img-thumbnail rounded-circle' %>
  <% end %>
  <span class="ml-1">
    <strong><%= post.user.name %></strong>
  </span>
  <% if policy(post).destroy? %>
    <span>
      <%= link_to fa_icon('trash', class: 'fa-2x'), post_path(post), method: :delete, class: 'float-right delete-post-item' %>
    </span>
  <% end %>
</div>

<%= image_tag url_for(post.photo), class: 'card-img-top' %>
<div class="card-body">
  <div class="row actions ml-0">
    <%= render 'likes_actions', { my_likes: @my_likes, post: post} %>
    <a href="#" class="core-sprite comment hide-text"></a>
    <% bookmark =  @my_bookmarks.select { |b| b.post_id == post.id }.first %>
      <%= render 'bookmark_actions', { bookmark: bookmark, post: post} %>
    </div>

    <%= render 'likes', { post: post} %>

    <p class="card-text">
      <span>
        <strong><%= post.user.name %></strong>
      </span>
      <%= post.content %></p>
    <hr/>

    <div id="comments-<%=post.id%>">
      <% post.comments.each do |comment| %>
        <%= render 'posts/comment', { comment: comment } %>
      <% end %>
    </div>
    <div class="row actions m-1" id="comments-form-<%=post.id%>">
      <%= render 'posts/comment_form', { comment: Comment.new, post: post } %>
    </div>
  </div>

  <div class="card-footer">
    <%= link_to 'Posted ' + time_ago_in_words(post.created_at) + ' ago', post %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items mt-3">
  <div class="col-xl-9 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create A Post
      </div>
      <div class="card-body">
        <%= form_with model: @post, local: true, multipart: true, class: 'post-upload dropzone needsclick dz-clickable p-0 border-0' do |form| %>
        <div class="form-group row mt-2">
          <div class="col-md-2 pr-0">
            <%= gravatar_image_tag current_user.email, gravatar: { size: 100 }, alt: 'Profile Picture', class: 'img-thumbnail rounded-circle' %>
          </div>
          <div class="col-md-10 pl-1">
            <div class="form-group">
              <%= form.text_field :content, class: 'form-control border-0', placeholder: 'Whats on your mind?' %>
            </div>
            <div class="dz-message needsclick d-flex flex-column justify-content-center">
              Drop files here or click to upload.
              <%= fa_icon("plus", class: 'fa-2x') %>
            </div>
            <div id="submit-post-button" class="submission pt-1">
              <%= form.submit 'Post', class: 'btn btn-outline-primary btn-block' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="mt-4">
    <h3 class="text-center">All Posts</h3>
    <div class="mt-4">
      <%= paginate @posts %>
    </div>
    <%= render @posts %>
  </div>

  <div class="mt-4">
    <%= paginate @posts %>
  </div>

</div>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-10 col-lg-11 col-xs-12">
    <div class="col-lg-8 col-md-7 px-0 d-flex">
      <div>
        <%= image_tag url_for(@post.photo), class: 'img-thumbnail rounded post-image' %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
      <div class="row px-3 d-flex justify-content-between">
        <div class="d-flex align-items-center">
          <%= link_to user_path(@post.user), class: 'no-text-decoration' do %>
          <%= gravatar_image_tag @post.user.email, gravatar: { size: 50 }, alt: 'Profile Picture', class: 'img-thumbnail rounded-circle' %>
        <% end %>
        <span class="ml-1">
          <strong><%= @post.user.name %></strong>
        </span>
      </div>

      <% if policy(@post).destroy? %>
        <%= link_to fa_icon('trash', class: 'fa-2x'), post_path(@post), method: :delete, class: 'float-right delete-post-item' %>
      <% end %>

    </div>
    <hr class="mb-0"/>
    <div class="comment-list py-2">
      <span>
        <strong><%= @post.user.name %></strong>
      </span>
      <span><%= @post.content %></span>
      <br/>

      <div id="comments-<%=@post.id%>">
        <% @post.comments.each do |comment| %>
          <%= render 'posts/comment', { comment: comment } %>
        <% end %>
      </div>
    </div>
    <hr class="mt-2"/>
    <div class="row actions ml-1 mr-1">
      <%= render 'likes_actions', { my_likes: @my_likes, post: @post} %>
      <a href="#" class="core-sprite comment hide-text"></a>
      <%= render 'bookmark_actions', {bookmark: @bookmark, post: @post} %>
    </div>
    <div class="mt-2 ml-1 mr-1">
      <%= render 'likes', { post: @post} %>
      <div>
        <%= 'Posted ' + time_ago_in_words(@post.created_at) + ' ago' %>
      </div>
    </div>
    <hr/>
    <div class="row actions ml-1 mr-1" id="comments-form-<%=@post.id%>">
      <%= render 'posts/comment_form', { comment: Comment.new, post: @post } %>
    </div>
  </div>
</div>
</div>